import type { Metadata } from "next";
import "./globals.css";
import Container from "@/components/Container";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: {
    default: "The Blog - Este é um blog criado com Next.js",
    template: "%s | The Blog",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Container>
      <Header />

        {children}

        <footer className="text-6xl font-bold text-center py-8">
        Footer
        </footer>
    </Container>
      </body>
    </html>
  );
}
